### ISSUE TITLE
Speler bewegen 

### ISSUE THREAD

**Issue by Volkan24** [informatica-emmauscollege/1920-4V-LEERLING-GAME-volkan-en-rajiv#1]
- 

- [x] Repository in gitpod halen.

- [x] Nieuwe branch maken en die branch in gitpod krijgen

- [x] Een speler maken.

- [x] Er voor zorgen dat je de speler met je pijltjes kan besturen

- [x] Zorg ervoor dat de speler niet verder gaat dan de randen
- [x] De speler veranderen in een spaceship

- [x] Overzetten naar de master

**Comment by Rajiv2004** [comment]
Meneer als wij via python3 -m http.server 3000 onze game willen bekijken, krijgen wij een wit scherm.

**Comment by Rajiv2004** [comment]
Meneer als wij de game willen bekijken staat er dat het nog aan het laden is
